config/routes.rb
Rails.application.routes.draw do
  

  resources :players 

  resources :games do
  resources :events
  end

  resources :leagues
  root "leagues#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
	enum action: {enter: 0, re_buy: 1, cash: 2}
	belongs_to :game
	belongs_to :player

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :league
	has_and_belongs_to_many :players
	has_many :events

	accepts_nested_attributes_for :events, allow_destroy: true
end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :players, through: :games
	has_many :games
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_and_belongs_to_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games/events_controller.rb
class Games::EventsController < ApplicationController
	before_filter :set_game

	def index
		@events = @game.events.all
	end
	def show
		@event = @game.event.find(params[:id])
	end
	def new
		@event = @game.build_event	
	end
	def create
		@event = Event.new(game_params)
		if @event.save
			redirect_to events_path 
		else
			render :new
		end
	end

	def destroy
		@event = @game.event.find(params[:id])
		@event.destroy
		redirct_to events_path
	end

  def event_params
    params.require(:event).permit(:game_id, :action, :amount, :player_id, :id)
	end

	def set_game
		@game = Game.find(params[:game_id])
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
		@games = Game.all
	end
	def show
		@game = Game.find(params[:id])
	end
	def new
		@game = Game.new	
	end
	def create
		@game = Game.new(game_params)
		if @game.save
			redirect_to games_path 
		else
			render :new
		end
	end

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])
		if @game.update(game_params)
			redirect_to games_path
		else
			render :edit
		end
	end

def destroy
		@game = Game.find(params[:id])
		@game.destroy
		redirect_to games_path
	end

private
  def game_params
    params.require(:game).permit(:date, :host, :id, player_ids: [])
	end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
	def index
		@leagues = League.all
	end
	def show
		@league = League.find(params[:id])
	end
	def new
		@league = League.new	
	end
	def create
		@league = League.new(league_params)
		if @league.save
			redirect_to leagues_path 
		else
			render :new
		end
	end

  def league_params
    params.require(:league).permit(:name)
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		@players = Player.all
	end
	def show
		@player = Player.find(params[:id])
	end
	def new
		@player = Player.new	
	end
	def create
		@player = Player.new(player_params)
		if @player.save
			redirect_to players_path 
		else
			render :new
		end
	end

  def player_params
    params.require(:player).permit(:first, :last, :handle, :address, :zip, :email)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/events/new.html.erb
<h3>What Happened?</h3>
<%= form_for (@event) do |f| %>
	<%=f.label(:game)%>
	<%=f.number_field(:game)%>
	<% end %>

app/views/games/_form.html.erb
<%= form_for (game) do |f| %>
<%= f.label :host%>
<%= f.text_field :host %><br>
<%= f.label :date%>
<%= f.date_field :date %>
<%= f.label :player_ids, "Players"%>
<%= f.collection_select :player_ids, Player.order(:last), :id, :last, {}, {multiple: true}%>

<%=f.submit %>


<% end %>

app/views/games/edit.html.erb
<%= render partial: 'form', locals: {game: @game} %>

app/views/games/index.html.erb
<h3> Game History</h3>

<% @games.each do |l| %>
	
	<tr>
		<td>
			<%= l.host %>
		</td>
		<td>
			<%= l.date %>
		</td>
		<td>
			<%= link_to "Show", l %>
			<%= link_to "Edit", edit_game_path(l) %>
			<%= link_to "Delete", l, method: :delete, data: {confirm: "Are you sure"} %>
		</td>
	</tr>
	<br>
		<%end%>
		<br>
		<%=link_to "New", new_game_path%>

app/views/games/new.html.erb
<%= render partial: 'form', locals: {game: @game} %>

app/views/games/show.html.erb
<h1><%=@game.host+' '+@game.date.to_s%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokrfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leagues/index.html.erb
<h1>Welcome to PokrFo</h1>

<h3> Please select a league</h3>

<% @leagues.each do |l| %>
	
	<tr>
		<td>
			<%= l.name %>
		</td>
		<%end%>

app/views/leagues/new.html.erb
<%= form_for (@league) do |f| %>
<%= f.label :name%>
<%= f.text_field :name %>
<%=f.submit %>
<% end %>

app/views/players/index.html.erb
<h3>Player List</h3>

<% @players.each do |p|%>
	
	<tr>
		<td>
			<%= p.first %>
		</td>
		<td>
			<%= p.last %>
		</td>
		<td>
			<%= p.handle %>
		</td>
		<td>
			<%= p.address %>
		</td>
		<td>
			<%= p.zip %>
		</td>
	</tr>
	<br>

<%end%>
		<br>
		<%= link_to "New", new_player_path%>

app/views/players/new.html.erb
<%= form_for (@player) do |f| %>
<%= f.label :first%>
<%= f.text_field :first %>
<%= f.label :last%>
<%= f.text_field :last %>
<%= f.label :handle%>
<%= f.text_field :handle %>
<%= f.label :address%>
<%= f.text_field :address %>
<%= f.label :zip%>
<%= f.number_field :zip %>
<%=f.submit %>
<% end %>